spring:
    datasource:
        initialization-mode: always
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://db:5432/patience 
        username: postgres
        password: P0stgr3s