spring:
    application:
      name: klondike
      
    datasource:
        initialization-mode: always
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres 
        username: postgres
        password: P0stgr3s
        
logging:
    level:
      root: INFO

server:
    port: 8001