version: "3.1"

services:
  db:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P0stgr3s
      POSTGRES_DB: patience
    
  amqp:
    image: rabbitmq:3.7-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  klondike: 
    build: 
      context: ./klondike
      dockerfile: Dockerfile
    ports: 
      - "8001:8001" 
    links: 
      - amqp
    depends_on: 
      - amqp
      - db
    volumes: 
      - "/tmp"    
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: amqp
   
  ui: 
    build: 
      context: ./ui
      dockerfile: Dockerfile
    depends_on: 
      - klondike
    ports:
      - "8000:80"
